[package]
name = "linfa"
version = "0.1.0"
authors = ["Luca Palmieri <rust@lpalmieri.com>"]
description = "A Machine Learning framework for Rust"
edition = "2018"
license = "MIT/Apache-2.0"

[dependencies]
linfa-clustering = { path = "linfa-clustering" }

[workspace]
members = ["linfa-clustering"]

[profile.release]
opt-level = 3
