[package]
name = "linfa"
version = "0.1.0"
authors = ["Luca Palmieri <rust@lpalmieri.com>"]
description = "A Machine Learning framework for Rust"
license = "MIT/Apache-2.0"

[dependencies]
ndarray = { version = "0.13" }
ndarray-rand = "0.11"
ndarray-stats = "0.3"
ndarray-npy = { version = "0.5", default-features = false }
rand_isaac = "0.2.0"

[workspace]
members = ["linfa-clustering", "python-bindings", "tonic-linfa-k-means"]

[profile.release]
opt-level = 3
